name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.GH_ACTIONS_SSH }}

      - name: Deploy to VPS
        run: |
          ssh -o StrictHostKeyChecking=no yahya@164.90.240.85 "
            cd /var/www/picraft &&
            git pull origin main &&
            cd ./PiCraft &&
            npm run build && 
            sudo systemctl restart flask-api.service
          "
